[workspace]
members=["common-types", "server"]
resolver="2"

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
schemars = "0.8.21"
serde = {version="1.0.210", features=["derive"]}
serde_json = "1.0.132"
